In [7]:
import sys,os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [8]:
net = simpleNet()
print(net.W)

[[ 0.22714766 -1.30423467  0.44921845]
 [ 0.59749898  0.12888778 -1.09884076]]


In [10]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[ 0.67403768 -0.6665418  -0.71942562]


In [11]:
np.argmax(p)

0

In [14]:
t = np.array([0, 0, 1])
net.loss(x, t)

1.8055115128411254

In [18]:
def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 値を元に戻す
        it.iternext()   
        
    return grad

In [19]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.39737492  0.10399062 -0.50136555]
 [ 0.59606238  0.15598594 -0.75204832]]
