In [2]:
import numpy as np
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [3]:
W[2]

array([6, 7, 8])

In [4]:
W[5]

array([15, 16, 17])

In [5]:
import numpy as np
np.random.choice(10)

4

In [6]:
np.random.choice(10)

5

In [7]:
words = ['you', 'say', 'goodbye', 'I', 'hello', '.']
np.random.choice(words)

'I'

In [8]:
np.random.choice(words, size=5)

array(['you', 'hello', 'I', 'I', '.'], dtype='<U7')

In [9]:
np.random.choice(words, size=5, replace=False)

array(['.', 'you', 'goodbye', 'say', 'I'], dtype='<U7')

In [10]:
p = [0.5, 0.1, 0.05, 0.2, 0.05, 0.1]
np.random.choice(words, p=p)

'.'

In [13]:
p = [0.7, 0.29, 0.01]
new_p = np.power(p, 0.75)
new_p /= np.sum(new_p)
print(new_p)

[0.64196878 0.33150408 0.02652714]


ModuleNotFoundError: No module named 'skip_gram'