In [6]:
import numpy as np
dxs = np.empty((15, 10, 5) , dtype='f')
print(dxs[:,0,:])

[[8.7135505e+32 6.5720898e-43 8.1987531e+32 6.5720898e-43 0.0000000e+00]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 9.2195630e-41 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3510607e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38 1.4012985e-45]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [0.0000000e+00 0.0000000e+00 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [0.0000000e+00 0.0000000e+00 2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [2.3694278e-38 2.3693558e-38 2.3694278e-38 2.3694278e-38 2.3694275e-38]
 [2.3693561e-38 2.3694278e-38 2.3693561e-38 9.21942